//! Traduce el keycode `evdev` (Linux, `input-event-codes.h`) que viaja por
//! el protocolo a un `VIRTUAL_KEY` de Windows. El emisor (X11 o Wayland)
//! siempre normaliza a `evdev` antes de mandarlo — ver
//! `x11::capture`/`wayland::capture` — así que este es el único lugar que
//! necesita conocer el mapeo Linux → Windows.
//!
//! Cubre el teclado estándar (letras, números, símbolos OEM, función,
//! navegación, numpad). Teclas multimedia/IME no mapeadas devuelven
//! `None` y simplemente no se inyectan.
use windows::Win32::UI::Input::KeyboardAndMouse::{
    VIRTUAL_KEY, VK_0, VK_1, VK_2, VK_3, VK_4, VK_5, VK_6, VK_7, VK_8, VK_9, VK_A, VK_ADD, VK_APPS,
    VK_B, VK_BACK, VK_C, VK_CAPITAL, VK_D, VK_DECIMAL, VK_DELETE, VK_DIVIDE, VK_DOWN, VK_E, VK_END,
    VK_ESCAPE, VK_F, VK_F1, VK_F10, VK_F11, VK_F12, VK_F2, VK_F3, VK_F4, VK_F5, VK_F6, VK_F7, VK_F8,
    VK_F9, VK_G, VK_H, VK_HOME, VK_I, VK_INSERT, VK_J, VK_K, VK_L, VK_LCONTROL, VK_LEFT, VK_LMENU,
    VK_LSHIFT, VK_LWIN, VK_M, VK_MULTIPLY, VK_N, VK_NEXT, VK_NUMLOCK, VK_NUMPAD0, VK_NUMPAD1,
    VK_NUMPAD2, VK_NUMPAD3, VK_NUMPAD4, VK_NUMPAD5, VK_NUMPAD6, VK_NUMPAD7, VK_NUMPAD8, VK_NUMPAD9,
    VK_O, VK_OEM_1, VK_OEM_2, VK_OEM_3, VK_OEM_4, VK_OEM_5, VK_OEM_6, VK_OEM_7, VK_OEM_COMMA,
    VK_OEM_MINUS, VK_OEM_PERIOD, VK_OEM_PLUS, VK_P, VK_PAUSE, VK_PRIOR, VK_Q, VK_R, VK_RCONTROL,
    VK_RETURN, VK_RIGHT, VK_RMENU, VK_RSHIFT, VK_RWIN, VK_S, VK_SCROLL, VK_SNAPSHOT, VK_SPACE,
    VK_SUBTRACT, VK_T, VK_TAB, VK_U, VK_UP, VK_V, VK_W, VK_X, VK_Y, VK_Z,
};

/// Traduce un keycode `evdev` a `VIRTUAL_KEY`. `None` si no hay mapeo
/// conocido (tecla rara/multimedia) — el llamador simplemente no inyecta
/// nada en vez de mandar una tecla equivocada.
#[must_use]
#[allow(clippy::too_many_lines)]
pub fn evdev_to_vk(keycode: u32) -> Option<VIRTUAL_KEY> {
    Some(match keycode {
        1 => VK_ESCAPE,
        2 => VK_1,
        3 => VK_2,
        4 => VK_3,
        5 => VK_4,
        6 => VK_5,
        7 => VK_6,
        8 => VK_7,
        9 => VK_8,
        10 => VK_9,
        11 => VK_0,
        12 => VK_OEM_MINUS,
        13 => VK_OEM_PLUS,
        14 => VK_BACK,
        15 => VK_TAB,
        16 => VK_Q,
        17 => VK_W,
        18 => VK_E,
        19 => VK_R,
        20 => VK_T,
        21 => VK_Y,
        22 => VK_U,
        23 => VK_I,
        24 => VK_O,
        25 => VK_P,
        26 => VK_OEM_4,
        27 => VK_OEM_6,
        28 | 96 => VK_RETURN,
        29 => VK_LCONTROL,
        30 => VK_A,
        31 => VK_S,
        32 => VK_D,
        33 => VK_F,
        34 => VK_G,
        35 => VK_H,
        36 => VK_J,
        37 => VK_K,
        38 => VK_L,
        39 => VK_OEM_1,
        40 => VK_OEM_7,
        41 => VK_OEM_3,
        42 => VK_LSHIFT,
        43 => VK_OEM_5,
        44 => VK_Z,
        45 => VK_X,
        46 => VK_C,
        47 => VK_V,
        48 => VK_B,
        49 => VK_N,
        50 => VK_M,
        51 => VK_OEM_COMMA,
        52 => VK_OEM_PERIOD,
        53 => VK_OEM_2,
        54 => VK_RSHIFT,
        55 => VK_MULTIPLY,
        56 => VK_LMENU,
        57 => VK_SPACE,
        58 => VK_CAPITAL,
        59 => VK_F1,
        60 => VK_F2,
        61 => VK_F3,
        62 => VK_F4,
        63 => VK_F5,
        64 => VK_F6,
        65 => VK_F7,
        66 => VK_F8,
        67 => VK_F9,
        68 => VK_F10,
        69 => VK_NUMLOCK,
        70 => VK_SCROLL,
        71 => VK_NUMPAD7,
        72 => VK_NUMPAD8,
        73 => VK_NUMPAD9,
        74 => VK_SUBTRACT,
        75 => VK_NUMPAD4,
        76 => VK_NUMPAD5,
        77 => VK_NUMPAD6,
        78 => VK_ADD,
        79 => VK_NUMPAD1,
        80 => VK_NUMPAD2,
        81 => VK_NUMPAD3,
        82 => VK_NUMPAD0,
        83 => VK_DECIMAL,
        87 => VK_F11,
        88 => VK_F12,
        97 => VK_RCONTROL,
        98 => VK_DIVIDE,
        99 => VK_SNAPSHOT,
        100 => VK_RMENU,
        102 => VK_HOME,
        103 => VK_UP,
        104 => VK_PRIOR,
        105 => VK_LEFT,
        106 => VK_RIGHT,
        107 => VK_END,
        108 => VK_DOWN,
        109 => VK_NEXT,
        110 => VK_INSERT,
        111 => VK_DELETE,
        119 => VK_PAUSE,
        125 => VK_LWIN,
        126 => VK_RWIN,
        127 => VK_APPS,
        _ => return None,
    })
}
